//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace AnotherOneConverter.WPF.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("AnotherOneConverter.WPF.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PDF Converter.
        /// </summary>
        public static string ApplicationTitle {
            get {
                return ResourceManager.GetString("ApplicationTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string ButtonDeleteDocumentTooltip {
            get {
                return ResourceManager.GetString("ButtonDeleteDocumentTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Down.
        /// </summary>
        public static string ButtonDownTooltip {
            get {
                return ResourceManager.GetString("ButtonDownTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to As.
        /// </summary>
        public static string ButtonExportAsContent {
            get {
                return ResourceManager.GetString("ButtonExportAsContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export As....
        /// </summary>
        public static string ButtonExportAsTooltip {
            get {
                return ResourceManager.GetString("ButtonExportAsTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1 As.
        /// </summary>
        public static string ButtonExportToOneAsContent {
            get {
                return ResourceManager.GetString("ButtonExportToOneAsContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export to One As....
        /// </summary>
        public static string ButtonExportToOneAsTooltip {
            get {
                return ResourceManager.GetString("ButtonExportToOneAsTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1.
        /// </summary>
        public static string ButtonExportToOneContent {
            get {
                return ResourceManager.GetString("ButtonExportToOneContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export to One.
        /// </summary>
        public static string ButtonExportToOneTooltip {
            get {
                return ResourceManager.GetString("ButtonExportToOneTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Excel File....
        /// </summary>
        public static string ButtonOpenExcelTooltip {
            get {
                return ResourceManager.GetString("ButtonOpenExcelTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Pdf File....
        /// </summary>
        public static string ButtonOpenPdfTooltip {
            get {
                return ResourceManager.GetString("ButtonOpenPdfTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Word File....
        /// </summary>
        public static string ButtonOpenWordTooltip {
            get {
                return ResourceManager.GetString("ButtonOpenWordTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Up.
        /// </summary>
        public static string ButtonUpTooltip {
            get {
                return ResourceManager.GetString("ButtonUpTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Changed.
        /// </summary>
        public static string ColumnChangedHeader {
            get {
                return ResourceManager.GetString("ColumnChangedHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Directory.
        /// </summary>
        public static string ColumnDirectoryNameHeader {
            get {
                return ResourceManager.GetString("ColumnDirectoryNameHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File Name.
        /// </summary>
        public static string ColumnFileNameHeader {
            get {
                return ResourceManager.GetString("ColumnFileNameHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Сonversion successfully completed..
        /// </summary>
        public static string ConvertationSuccessMessage {
            get {
                return ResourceManager.GetString("ConvertationSuccessMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Success!.
        /// </summary>
        public static string ConvertationSuccessTitle {
            get {
                return ResourceManager.GetString("ConvertationSuccessTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to , Converting &apos;{0}&apos;....
        /// </summary>
        public static string ConvertingFormat {
            get {
                return ResourceManager.GetString("ConvertingFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t convert file &apos;{0}&apos;.
        /// </summary>
        public static string ErrorConversationFailed {
            get {
                return ResourceManager.GetString("ErrorConversationFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error.
        /// </summary>
        public static string ErrorTitle {
            get {
                return ResourceManager.GetString("ErrorTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All.
        /// </summary>
        public static string FilterAllTitle {
            get {
                return ResourceManager.GetString("FilterAllTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        public static System.Drawing.Icon LogoIcon {
            get {
                object obj = ResourceManager.GetObject("LogoIcon", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close Project.
        /// </summary>
        public static string MenuItemCloseProjectHeader {
            get {
                return ResourceManager.GetString("MenuItemCloseProjectHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exit.
        /// </summary>
        public static string MenuItemExitHeader {
            get {
                return ResourceManager.GetString("MenuItemExitHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export As....
        /// </summary>
        public static string MenuItemExportAsHeader {
            get {
                return ResourceManager.GetString("MenuItemExportAsHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export.
        /// </summary>
        public static string MenuItemExportHeader {
            get {
                return ResourceManager.GetString("MenuItemExportHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export to One As....
        /// </summary>
        public static string MenuItemExportToOneAsHeader {
            get {
                return ResourceManager.GetString("MenuItemExportToOneAsHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export to One.
        /// </summary>
        public static string MenuItemExportToOneHeader {
            get {
                return ResourceManager.GetString("MenuItemExportToOneHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File.
        /// </summary>
        public static string MenuItemFileHeader {
            get {
                return ResourceManager.GetString("MenuItemFileHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Project.
        /// </summary>
        public static string MenuItemNewProjectHeader {
            get {
                return ResourceManager.GetString("MenuItemNewProjectHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open File....
        /// </summary>
        public static string MenuItemOpenFileHeader {
            get {
                return ResourceManager.GetString("MenuItemOpenFileHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Project....
        /// </summary>
        public static string MenuItemOpenProjectHeader {
            get {
                return ResourceManager.GetString("MenuItemOpenProjectHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project.
        /// </summary>
        public static string MenuItemProjectHeader {
            get {
                return ResourceManager.GetString("MenuItemProjectHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Project As....
        /// </summary>
        public static string MenuItemSaveProjectAsHeader {
            get {
                return ResourceManager.GetString("MenuItemSaveProjectAsHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save Project.
        /// </summary>
        public static string MenuItemSaveProjectHeader {
            get {
                return ResourceManager.GetString("MenuItemSaveProjectHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Settings.
        /// </summary>
        public static string MenuItemSettingsHeader {
            get {
                return ResourceManager.GetString("MenuItemSettingsHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export.
        /// </summary>
        public static string PopupBoxExportTooltip {
            get {
                return ResourceManager.GetString("PopupBoxExportTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open File....
        /// </summary>
        public static string PopupBoxOpenTooltip {
            get {
                return ResourceManager.GetString("PopupBoxOpenTooltip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project Settings.
        /// </summary>
        public static string ProjectSettingsFlyoutHeader {
            get {
                return ResourceManager.GetString("ProjectSettingsFlyoutHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Project name.
        /// </summary>
        public static string ProjectSettingsNameTitle {
            get {
                return ResourceManager.GetString("ProjectSettingsNameTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sync folders.
        /// </summary>
        public static string ProjectSettingsSyncFilesTitle {
            get {
                return ResourceManager.GetString("ProjectSettingsSyncFilesTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sync.
        /// </summary>
        public static string SyncDocumentsTooltip {
            get {
                return ResourceManager.GetString("SyncDocumentsTooltip", resourceCulture);
            }
        }
    }
}
